### ISSUE TITLE
这个命令在哪里执行，我已经在cloudflare部署，但是部署的网站打不开

### ISSUE THREAD

**Issue by llds66** [jw-12138/cwgi-docs#3]
![image](https://github.com/user-attachments/assets/c6009cc5-92b0-4d3d-a257-bb0bb81cd224)
![image](https://github.com/user-attachments/assets/b837b3b1-e3d1-420e-b6f8-08dd7e5ccf77)

**Comment by llds66** [comment]
上面配置好了，但是页面github登录,回调显示
![image](https://github.com/user-attachments/assets/9990aec4-0882-473f-b78f-82a2abe963b6)

**Comment by jw-12138** [comment]
@llds66 

1. bun可以理解为另一种npm，如果你不习惯用bun，跑`npm run deploy`即可
2. `access_token`是`undefined`大概率是因为你的worker配置错了，建议严格按照[server-side](https://cwgi-docs.jw1.dev/server-side/)教程再走一遍
3. `cwgi-cli`是客户端代码而不是服务端代码，所以回调地址应该是一张静态页面（可以访问document）而不是一个API

**Comment by llds66** [comment]
@jw-12138  
谢谢回复，我已经在cloudflare部署服务器端代码，并设置自定义域名 `https://llds.fun`，直接在浏览器输入回调地址`https://llds.fun`返回: Hello CWGI!、回调地址`https://llds.fun/`返回: {"error":"Missing redirect URL"}，服务端代码应该没问题。现在评论可以正常显示，点击登录会返回redirect_uri错误。请您有空帮助我一下，非常感谢！以下是相关截图。
![image](https://github.com/user-attachments/assets/1d9d4c5e-4163-4e5e-ad21-8fb2624626d0)

**这个是github app的配置：**
![image](https://github.com/user-attachments/assets/fc58cd70-0d6c-47e9-8773-52e6f959cf9d)

**这个是客户端代码**
![image](https://github.com/user-attachments/assets/6ef86411-546b-4ee5-b02d-fb28973bbe28)

**Comment by jw-12138** [comment]
@llds66 是我这边的问题，我客户端代码里写死了这个redirect_url(🥶你是第一个用户)，新代码已经push了。你现在应该只需要做两件事：

1. 重新下载cwgi.js
2. 设置`options.proxy`为`https://llds.fun`

顺便借你的网站我调整一下样式，看来有些样式还是没有cover到哈哈哈

**Comment by llds66** [comment]
@jw-12138  我只修改proxy,评论没有显示，登录也是上述错误。我现在只在cloudflare部署的是cwgi-api，（教程里应该是cwgi-api），我还需要配置别的仓库吗 ，比如这个？[cwgi-cli](https://github.com/jw-12138/cwgi-cli)，我是不是哪里还没配置？🥺
![image](https://github.com/user-attachments/assets/115e4f1a-03b7-469a-953a-eb3f16b3c4c7)
![image](https://github.com/user-attachments/assets/4ceadb14-8ef6-4b0d-a561-5d387b402942)

**Comment by jw-12138** [comment]
@llds66  我刚刚编辑了一下评论所以你可能没看到，我看到你引用的cwgi.js是本地路径，所以你可能需要下载最新版本的js文件。

新版本会在外面盒子上插入一个version：

<img width="622" alt="image" src="https://github.com/user-attachments/assets/e63554a7-abc1-428c-a3a1-1a4186334873">

**Comment by jw-12138** [comment]
@llds66 如果url正确，token是能正常返回的，但是你的nuxt路由可能出了点问题(进入博客页刷新也会报http 500的错误)，这个就要靠你自己去解决了🤔

<img width="1026" alt="image" src="https://github.com/user-attachments/assets/eb1368ba-a202-4b42-844e-5736d2e7146d">

**Comment by llds66** [comment]
@jw-12138 好的，佬，确实我的路由有问题（还不知道怎么配置🥲）
现在遇到的问题：
1. 配置proxy为我的回调地址，登录成功后可以正常返回token,像您的示例图一样。问题：**评论数据请求不到**。（GitHub app 回调为我的地址）
![image](https://github.com/user-attachments/assets/62d07104-13d7-4e86-bad7-bcf1aad4cfe5)

2. 不配置proxy,评论数据有，点击登录出现登录github账号，登录成功：（githb app 配置成您的回调，登录token为access_token=undefined&scope=undefined&token_type=undefined）
![image](https://github.com/user-attachments/assets/7cf484af-f55f-48be-9099-ce68a63a5a17)

**Comment by jw-12138** [comment]
@llds66 不使用proxy下的问题我明天再看看，推荐还是用proxy，这样用户体验会好很多。你这里http 400在控制台看不出任何原因，可以看一下devTools的network栏里对应的请求返回了什么吗？

**Comment by llds66** [comment]
@jw-12138 这样的 早点休息，麻烦了
![image](https://github.com/user-attachments/assets/71977299-b1ea-49ac-bede-963a15fa9ac9)
![image](https://github.com/user-attachments/assets/0516db5e-34e1-4a7a-bb27-681d3656ebdc)

**Comment by jw-12138** [comment]
@llds66 应该是 workers 没有配置环境变量，可以去看一下你部署的 cwgi-api 下的`wrangler.toml`, `SITE_URL`应该是你自己的博客`https://llds.cc`，修改完之后再重新deploy一下就好了。

<img width="759" alt="image" src="https://github.com/user-attachments/assets/870a246b-8422-4d44-969b-38040688f6aa">

**Comment by llds66** [comment]
@jw-12138 
我想我的问题已经解决，我把网站部署后，评论与登录都正常了，（登录成功后有token,但是页面不正确，应该是我的Nuxt路由的问题）。但是在本地运行还是评论400.
非常感谢解答！！非常感谢
😊

**Comment by jw-12138** [comment]
@llds66 本地应该也是一样的问题，在ALLOWED_ORIGINS里面定义就好。

<img width="953" alt="image" src="https://github.com/user-attachments/assets/b15c4c80-1002-4d4c-90cb-7d9585ca48e9">

**Comment by llds66** [comment]
提交评论403 ，ALLOWED_ORIGINS配置的`*`,这是什么原因呀
![image](https://github.com/user-attachments/assets/f3ffad4f-bb65-4182-bf52-9496f66f1ce4)
![image](https://github.com/user-attachments/assets/618a6dbc-55ba-4d11-b948-a93889929c5c)

**Comment by jw-12138** [comment]
`ALLOWED_ORIGINS`不支持glob pattern，必须平铺出来并且用`,`分割，当中没有空格

**Comment by jw-12138** [comment]
@llds66 github app 是不是没有安装在你的github账号下？

教程：https://cwgi-docs.jw1.dev/github-app/#install-the-app

<img width="854" alt="image" src="https://github.com/user-attachments/assets/6bce2355-277b-4222-ba8e-48af0070f6d6">

**Comment by llds66** [comment]
在我的账号下
![image](https://github.com/user-attachments/assets/abe6be3b-215a-4b75-b516-3a718df4d93b)
我更改了`ALLOWED_ORIGINS`，还是没有成功,我在仔细核对一下，或者重新配置一个app
![image](https://github.com/user-attachments/assets/680523ba-a810-4b16-aa18-d2db370fd45d)

**Comment by jw-12138** [comment]
@llds66 

`ALLOWED_ORIGINS`设置为`*`是没问题的，你的GitHub App权限没有选对。

需要Issues的Read & Write权限才可以。

<img width="317" alt="image" src="https://github.com/user-attachments/assets/ba43d7f8-da27-4d91-92b0-b9e03fdde478">

**Comment by llds66** [comment]
@jw-12138 可以成功评论了，感谢您解答这么多我的问题，太感谢了！
